[build]
  publish = "public"
  functions = "netlify/functions"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://www.themagickmechanic.com"
    Access-Control-Allow-Methods = "GET"
